// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calcCorr
void calcCorr(CharacterVector fls, int MaxNameLen, int recSize, int P, int n, double zeroSD);
RcppExport SEXP _betaMix_calcCorr(SEXP flsSEXP, SEXP MaxNameLenSEXP, SEXP recSizeSEXP, SEXP PSEXP, SEXP nSEXP, SEXP zeroSDSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fls(flsSEXP);
    Rcpp::traits::input_parameter< int >::type MaxNameLen(MaxNameLenSEXP);
    Rcpp::traits::input_parameter< int >::type recSize(recSizeSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type zeroSD(zeroSDSEXP);
    calcCorr(fls, MaxNameLen, recSize, P, n, zeroSD);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_betaMix_calcCorr", (DL_FUNC) &_betaMix_calcCorr, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_betaMix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
