# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate pairwise correlations and print to a file.
#'
#' @param fls A character vector which includes the names of the input and output files.
#' @param MaxNameLen The length of the first column in the input data file (predictor names).
#' @param recSize The total length of input rows (fixed-width format).
#' @param P The number of predictors.
#' @param n The sample size.
#' @param zeroSD If the standard deviation of a column is below this threshold, this column will be considered as uncorrelated with all other columns (Default=1e-3).
calcCorr <- function(fls, MaxNameLen, recSize, P, n, zeroSD = 1e-3) {
    invisible(.Call('_betaMix_calcCorr', PACKAGE = 'betaMix', fls, MaxNameLen, recSize, P, n, zeroSD))
}

